import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const generalSansLight = localFont({
  src: "./fonts/general-sans/GeneralSans-Light.woff",
  variable: "--font-general-sans-light",
  weight: "300",
});

const generalSansRegular = localFont({
  src: "./fonts/general-sans/GeneralSans-Regular.woff",
  variable: "--font-general-sans-regular",
  weight: "400",
});

const generalSansMedium = localFont({
  src: "./fonts/general-sans/GeneralSans-Medium.woff",
  variable: "--font-general-sans-medium",
  weight: "500",
});

const generalSansSemibold = localFont({
  src: "./fonts/general-sans/GeneralSans-Semibold.woff",
  variable: "--font-general-sans-semibold",
  weight: "600",
});

const generalSansBold = localFont({
  src: "./fonts/general-sans/GeneralSans-Bold.woff",
  variable: "--font-general-sans-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "BYOP - Build Your Own Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`dark ${generalSansLight.variable} ${generalSansRegular.variable} ${generalSansMedium.variable} ${generalSansSemibold.variable} ${generalSansBold.variable} antialiased dark:bg-[#09090b] dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}

